// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ibf
void ibf(IntegerVector renewal, unsigned int Hmax, unsigned int alphlen);
RcppExport SEXP _ibfvlmc_ibf(SEXP renewalSEXP, SEXP HmaxSEXP, SEXP alphlenSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type renewal(renewalSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type Hmax(HmaxSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type alphlen(alphlenSEXP);
    ibf(renewal, Hmax, alphlen);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ibfvlmc_ibf", (DL_FUNC) &_ibfvlmc_ibf, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ibfvlmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
